### ISSUE TITLE
Manifest inconsistency

### ISSUE THREAD

**Issue by jaruba** [NivM1/podcasts-for-all#2]
**Describe the bug**
You are using a type for your catalog:
https://github.com/NivM1/podcasts-for-all/blob/master/common/const.js#L64

That is not declared in manifest.types:
https://github.com/NivM1/podcasts-for-all/blob/master/manifest.js#L67-L69

I believe this might be the reason the "Podcasts" type only shows on the Desktop app, but not in the Android app.

**To Reproduce**
1. Go to 'Stremio Android - Add-ons Page'
2. Click on 'Install from Podcasts for All'
3. Go to 'Discover page'
4. 'Podcasts' type won't be there

**Expected behavior**
See 'Podcasts' type on Android

**Screenshots**
nope

**Desktop (please complete the following information):**
 - OS: Android
 - Browser: Nope
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: Any Android
 - OS: Any Android
 - Browser: Nope
 - Version: Whichever

**Additional context**
Nope

**Comment by NivM1** [comment]
Hi @jaruba ! 
Thank you for openning this  issue.
I had already [fix it](https://github.com/NivM1/podcasts-for-all/commit/e0dd8c74beb9de0db714e341e92f39b1966be8f5) as you recommend and **now it's working on the Android app.**
So Cool!
Thank you!
